version: "3"

services:
  scibib:
    container_name: scibib
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SCIBIB_MYSQL_DATABASE=${SCIBIB_MYSQL_DATABASE}
        - SCIBIB_MYSQL_USER=${SCIBIB_MYSQL_USER}
        - SCIBIB_MYSQL_PASSWORD=${SCIBIB_MYSQL_PASSWORD}
        - SCIBIB_MYSQL_HOST=${SCIBIB_MYSQL_HOST}
        - SCIBIB_EMAIL_SENDER=${SCIBIB_EMAIL_SENDER}
        - SCIBIB_BIND_ADDRESS=${SCIBIB_BIND_ADDRESS}
        - SCIBIB_BIND_PORT=${SCIBIB_BIND_PORT}
        - MAIL_SERVER=${MAIL_SERVER}
        - MAIL_PORT=${MAIL_PORT}
        - MAIL_USE_SSL=${MAIL_USE_SSL}
        - MAIL_USERNAME=${MAIL_USERNAME}
        - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
        - SECRET=${SECRET}
        - BEHIND_PROXY=${BEHIND_PROXY}
    volumes:
      - ./app/frontend/static/uploadedFiles:/srv/scibib/frontend/static/uploadedFiles
    ports:
      - ${SCIBIB_BIND_ADDRESS}:${SCIBIB_BIND_PORT}:8080
